services:
  postgres:
    image: postgres:latest
    container_name: mine3-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: mine3-redis
    ports:
      - "6379:6379"
  mine3_frontend:
    build:
      context: ./mine3-frontend
      dockerfile: Dockerfile
    container_name: mine3-frontend
    ports:
      - "5173:80"
