# Mine3
# Minecraft Authentication with web3 wallet (EVM)
# Repository: https://github.com/boomchanotai/Mine3
# Author: Boom Chanotai (https://www.boomchanotai.com/)

# Redis Settings
redis:
  host: "localhost"
  port: 6379

# Httpserver Settings
httpserver:
  port: 4000

# Authentication Settings
auth:
  website_token_base_url: "http://localhost:5173/login?token="
  login_session_timeout: 600 # sec
  token_prefix_key: "mine3:auth:token" # redis key (string) follow with :{token}
  click_to_login_message: "Click here to login!"
  prevent_action_message: "Please connect to your wallet!"
  join_server_title:
    title: "&9Mine3"
    subtitle: "&fPlease login with your wallet!"
    fade_in: 10
    stay: 70
    fade_out: 20
  logged_in_title:
    title: "&9Mine3"
    subtitle: "&aLogin Successful!"
    fade_in: 10
    stay: 70
    fade_out: 20
  force_respawn: false

# Join Quit Server Settings
# {address} = Ethereum Address
join_message: "&e{address} joined the game."
quit_message: "&e{address} left the game."
