name: Mine3Auth
version: "${project.version}"
main: com.boomchanotai.mine3Auth.Mine3Auth
api-version: "1.21"
description: "minecraft authentication system with evm wallet"
author: boomchanotai
website: https://github.com/boomchanotai/Mine3
depend: [Mine3Lib]
commands:
  address:
    description: get address
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> - get player's address
      /<command> <player> - get other player's address
  logout:
    description: logout
    usage: /<command>
  auth:
    description: mine3 command
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> spawn - go to spawn point
      /<command> setspawn - set spawn point (admin only)
  auth spawn:
    description: go to spawn point
    usage: /<command> spawn
  auth setspawn:
    description: set spawn point on player join
    usage: /<command> setspawn
    permission: "mine3.setspawn"
    permission-message: You don't have permission to use this command
  ban:
    description: ban player
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> <player> - ban player
      /<command> <player> <reason> - ban player with reason
permissions:
  mine3.auth.setspawn:
    description: allow player to set spawn point
  mine3.ban:
    description: allow player to ban other player
