# Mine3Standard
# Minecraft Authentication with web3 wallet (EVM)
# Repository: https://github.com/boomchanotai/Mine3
# Author: Boom Chanotai (https://www.boomchanotai.com/)

# Plugins settings
color_code_prefix: "&" # Color code prefix

teleport_timeout: 300 # Teleport timeout in seconds
