# Mine3Standard
# Minecraft Authentication with web3 wallet (EVM)
# Repository: https://github.com/boomchanotai/Mine3
# Author: Boom Chanotai (https://www.boomchanotai.com/)

# Plugins settings
# Chat title when plugin send message to player
title: "&9[Mine3] &7"
# Color code prefix
color_code_prefix: "&"
