name: Mine3Standard
version: "1.0-SNAPSHOT"
main: com.boomchanotai.mine3Standard.Mine3Standard
api-version: "1.21"
authors: [BoomChanotai]
description: Mine3Lib
website: https://boomchanotai.com
depend: [Mine3Lib]
commands:
  tp:
    description: Teleport to player
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> <address> - teleport to other player
      /<command> <address> <player> - teleport player to player
  give:
    description: Give item to player
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> <address> <item> <item> - give item to player
  gamemode:
    description: Change player gamemode
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> <gamemode> - change player gamemode
      /<command> <gamemode> <address> - change other player gamemode
permissions:
  mine3.tp:
    description: allow player to teleport to player
  mine3.tp.others:
    description: allow other player to teleport other player
  mine3.give:
    description: allow player to give item to player
  mine3.gamemode:
    description: allow player to change gamemode
  mine3.gamemode.others:
    description: allow other player to change other player gamemode
